### ISSUE TITLE
Zoom is keeping center of the map as focus area

### ISSUE THREAD

**Issue by Tokeiito** [xorith/MapViewer#1]
basically when users navigates map's, they are used to functionality, that zoom in and out is done on the spot where mouse pointer is. Here it is done on the center of image/map.

**Comment by keenan-v1** [comment]
Thank you for the report!

I've improved zooming in somewhat, but it still doesn't base off of the mouse. I'm hoping to have that for next release. My main focus on this one was to get some translating done between mouse X, Y and Map X, Y so I can display map information. :)

Going to leave this open as a reminder though!

**Comment by keenan-v1** [comment]
Closing, fix committed in 1.3
